name: flutterwhatsappclone
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.8

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons:
  intl_phone_number_input: ^0.4.6+2
  dashed_circle: ^0.0.1
  custom_switch: ^0.0.1
  shared_preferences: ^0.5.12+4
  intl: ^0.16.0
  fluttertoast: ^3.1.3
  auto_size_text: ^2.0.2
  provider: ^4.3.2
  image_picker: ^0.6.2+1
  circular_profile_avatar: ^1.0.6
  cached_network_image: ^2.3.2+1
  file_picker: ^1.4.3+2
  toast: ^0.1.5
  cloud_firestore: any
  firebase_auth: ^0.16.1
  firebase_database: ^3.0.7
  firebase_messaging: 6.0.13
  firebase_storage: ^3.1.3
  flutter_screenutil: ^0.4.2
  google_sign_in: ^4.5.1
  timeago: ^2.0.26
  flutter_slidable: ^0.5.4
  flutter_spinkit: ^4.1.2+1
  video_player: ^0.10.11+2
  image_cropper: ^1.2.3
  inview_notifier_list: ^1.0.0
  photo_view: ^0.9.2
  contacts_service: ^0.4.6
  dio: ^3.0.10
  url_launcher: ^5.7.1
  flutter_audio_recorder: ^0.5.5
  audioplayers:
  flutter_countdown_timer: ^3.0.0
  permission_handler:
  maps_launcher: ^1.2.0
  carousel_slider: ^2.2.1
  screenshot:
  google_fonts: ^1.1.1
  agora_rtc_engine: ^4.0.6
  connectivity: ^3.0.4
  rflutter_alert: ^1.0.3
  percent_indicator: ^2.1.9+1
  video_compress: ^2.1.0
  flutter_image_compress: ^0.7.0
  swipedetector:
  flutter_linkify: ^4.0.2
  bubble: ^1.1.9+1
  linkable: ^1.0.7
  stop_watch_timer: ^0.6.0+1
  substring_highlight: ^0.1.2
  scroll_to_index:
  multi_image_picker: ^4.8.0
  flutter_absolute_path: ^1.0.6
  swipeable: ^1.1.0
  giphy_get:
  share: ^2.0.1
  flutter_statusbarcolor: ^0.2.3
  progress_dialog: ^1.2.1
  image_editor_pro: 1.0.9
  flutter_local_notifications:
  place_picker:
  flutter_chat_bubble: ^2.0.0
  visibility_detector: ^0.2.0
  flick_video_player: 



dev_dependencies:
  flutter_launcher_icons: ^0.7.4
  flutter_test:
    sdk: flutter


flutter_icons:
  image_path: "assets/images/applogo.png" 
  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/audio/
    - data/

  fonts:
    - family: Montserrat  
      fonts:
        - asset: assets/fonts/Montserrat.ttf
    - family: Poppins-Medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
    - family: MontserratBold
      fonts:
        - asset: assets/fonts/MontserratBold.ttf
 

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
